spring.profiles.active=local
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.username=sa

# jdbcTemplate sql log
logging.level.org.springframework.jdbc=debug

# MyBatis
# mybatis.type-aliases-package
    # \uB9C8\uC774\uBC14\uD2F0\uC2A4\uC5D0\uC11C \uD0C0\uC785 \uC815\uBCF4\uB97C \uC0AC\uC6A9\uD560 \uB54C\uC5D0\uB294 \uD328\uD0A4\uC9C0 \uC774\uB984\uC744 \uC801\uC5B4\uC918\uC57C \uD558\uB294\uB370, \uC5EC\uAE30\uC5D0 \uBA85\uC2DC\uD558\uBA74 \uD328\uD0A4\uC9C0 \uC774\uB984\uC744 \uC0DD\uB7B5\uD560 \uC218 \uC788\uB2E4.
    # \uC9C0\uC815\uD55C \uD328\uD0A4\uC9C0\uC640 \uADF8 \uD558\uC704 \uD328\uD0A4\uC9C0\uAC00 \uC790\uB3D9\uC73C\uB85C \uC778\uC2DD\uB41C\uB2E4.
    # \uC5EC\uB7EC \uC704\uCE58\uB97C \uC9C0\uC815\uD558\uB824\uBA74 ',', ';'\uB85C \uAD6C\uBD84\uD558\uBA74 \uB41C\uB2E4.
mybatis.type-aliases-package=hello.itemservice.domain
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.hello.itemservice.repository.mybatis=trace